apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rogoyalaks1-5582"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rogoyalaks1-5582"
  template:
    metadata:
      labels:
        app: "rogoyalaks1-5582"
    spec:
      containers:
        - name: "rogoyalaks1-5582"
          image: "rogoyalacr.azurecr.io/rogoyalaks1"
          ports:
          - containerPort: 80